eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

feign:
  hystrix:
     enabled: true;

server:
  port: 5555
  context-path: /SpringCloudFeignCsm
  session:
    timeout: 30