spring:
  application:
    name: SpringCloudConsul
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        enabled: true
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 15s
        instance-id: consul-miya
server:
  port: 5566

