eureka:
  client:
    service-url:
       defaultZone: http://localhost:9999/eureka/

zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: SpringCloudConsumer
    feign:
      path: /feign/**
      serviceId: SpringCloudFeignCsm